version: 0.2

env:
  variables:
    IMAGE_REPO: "976193254957.dkr.ecr.us-east-1.amazonaws.com/my-node-app"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR...."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $IMAGE_REPO
      - echo "Installing ArgoCD CLI..."
      - curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
      - chmod +x /usr/local/bin/argocd

  build:
    commands:
      - echo "Building Docker image..."
      - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # ✅ Ensure IMAGE_TAG is set
      - echo "Image Tag: $IMAGE_TAG"
      - docker build -t $IMAGE_REPO:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $IMAGE_REPO:$IMAGE_TAG
      - echo "Image pushed successfully: $IMAGE_TAG"

      - echo "Logging into ArgoCD..."
      - argocd login 192.168.32.59:30080 --username ${ARGOCD_USERNAME} --password ${ARGOCD_PASSWORD} --insecure

      - echo "Updating image repository in ArgoCD..."
      - argocd --grpc-web app set my-node-app -p image.repository=$IMAGE_REPO
      - argocd --grpc-web app set my-node-app -p image.tag=$IMAGE_TAG

      - echo "Triggering ArgoCD sync..."
      - argocd app sync my-node-app

artifacts:
  files: "**/*"
