version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 976193254957.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo Installing ArgoCD CLI for ARM64...
      - curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/download/v2.6.4/argocd-linux-arm64
      - chmod +x argocd
      - mv argocd /usr/local/bin/
      - ls -lah /usr/local/bin/argocd



  build:
    commands:
      - echo "Building the Docker image..."
      - REPO_URI=976193254957.dkr.ecr.us-east-1.amazonaws.com/base
      - ls
      - pwd
      - docker build -t $REPO_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker images
      - docker push $REPO_URI:$IMAGE_TAG
      - echo "Push completed"
      - echo Logging into ArgoCD...
      - argocd login 192.168.32.59:30080  --username ${ARGOCD_USERNAME} --password ${ARGOCD_PASSWORD} --insecure
      - echo Updating image repository in ArgoCD...
      - argocd --grpc-web app set nodejs-app -p image.repository=976193254957.dkr.ecr.us-east-1.amazonaws.com/base
      - echo Setting image tag in ArgoCD...
      - argocd --grpc-web app set nodejs-app -p image.tag=$IMAGE_TAG
      - echo Triggering ArgoCD sync...
      - argocd app sync nodejs-app --revision $IMAGE_TAG

artifacts:
  files: "**/*"
